### ISSUE TITLE
Error adding todo

### ISSUE THREAD

**Issue by axonxorz** [MuntasirSauvik/WebDevelopmentBootcamp#3]
I have deleted a few items from the Todo list (v2), but am unable to create new ones:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'items' of null
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/app.js:105:17
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/mongoose/lib/model.js:4846:16
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/mongoose/lib/model.js:4846:16
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/mongoose/lib/model.js:4869:21
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/mongoose/lib/query.js:4424:11
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/kareem/index.js:135:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on Function instance at:
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/mongoose/lib/model.js:4848:13
    at /home/bzerr/tmp/WebDevelopmentBootcamp/todolist-v2/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    [... lines matching original stack trace ...]
```

**Comment by MuntasirSauvik** [comment]
Resolved it, it was a problem in the list.ejs, the button was missing a value 
"    <button type="submit" name="list" value="<%= listTitle %>">+</button>", this is the correction.
